# Define required macros here
SHELL = /bin/sh

#Directory/Directories that house source .c files
OBJDIR = src/
LIBS=-lm

#Header Directory for header files
INCLUDEDIR=./header
INCLUDES=-I${INCLUDEDIR}

#collects source files from their respective Directories
SOURCES =	$(wildcard *.c)
SOURCES +=	$(wildcard $(OBJDIR)*.c)

#can be used for object file creation but object files did not seem to compile correct
#$(wildcard *.o): $(wildcard *.c)
#	${CC} $(CFLAGS) $(INCLUDE) -o $<

#Executable file declaration
#change helloworld to desired executable name
helloworld:${SOURCES}
	${CC} ${CFLAGS} ${INCLUDES} -o $@ ${SOURCES} ${LIBS}


.PHONY: clean
clean:
	-rm -f *.o core *.core
